export const ADD_TASK = "ADD_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const UPDATE_TITLE_TASK = "UPDATE_TITLE_TASK";
export const UPDATE_COMPLETED_TASK = "UPDATE_COMPLETED_TASK";
export const UPDATE_FINISHED_TASK = "UPDATE_FINISHED_TASK";